### ISSUE TITLE
Latest version does not work

### ISSUE THREAD

**Issue by herobrine30396** [siddhrsh/Twrp_RMX1941#11]
I tried flashing the latest version, and then tried to boot into TWRP, but the phone restarts and boots to the system. I tried flashing 3.5.0 later, and that works though.

**Comment by SIDDK24** [comment]
Which version you downloading for A10 or A9?

**Comment by herobrine30396** [comment]
A11

**Comment by herobrine30396** [comment]
So, does the A9 version support crypto? Cause if it did, I wouldn't mind downgrading to A9

**Comment by SIDDK24** [comment]
On A9 encryption dead no supported
On A10 only rmui decryption supported

**Comment by herobrine30396** [comment]
Ok, so A11 supports coloros decryption?

**Comment by gaurav7209** [comment]
If you are at cos android 9 
Then use :-
https://sourceforge.net/projects/realme-c2/files/ColorOS/TWRP/


And if you are at rmui android 10 
Then use :- 
https://sourceforge.net/projects/realme-c2/files/RealmeUI/TWRP/


Hope this will help you
